export interface IUserModel {
   id: Number;
   password: string;
   roleNames: Array<string>;
   isActive: Boolean;
   allowedLeaveDay: Number;
   branch: Number;
   userName: string;
   emailAddress: string;
   type: Number;
   name: string;
   surname: string;
   sex: Boolean;
   userCode: string;
   isStopWork: Boolean;
   managerId: Number;
   level: Number;
   salary: Number;
   salaryAt: string;
   address: string;
   phoneNumber: string;
   morningStartAt: string;
   morningEndAt: string;
   morningWorking: Number;
   afternoonStartAt: string;
   afternoonEndAt: string;
   afternoonWorking: Number;
   createdAt: Date;
   jobTitle: string;
   avartarPath: string;
   generateAuthToken: () => Promise<string>;
   comparePassHash: (plainPass: string) => Promise<Boolean>;
}
