export interface IUserModel {
   id: Number;
   password: String;
   userName: String;
   name: String;
   surname: String;
   fullName: String;
   emailAddress: String;
   phoneNumber: String;
   address: String;
   isActive: Boolean;
   roleNames: Array<string>;
   projectUsers: Array<Object>;
   type: Number;
   salary: Number;
   salaryAt: String;
   startDateAt: Date;
   allowedLeaveDay: Number;
   userCode: String;
   jobTitle: String;
   level: Number;
   registerWorkDay: Number;
   avatarPath: String;
   managerId: Number;
   managerAvatarPath: String;
   managerName: String;
   branch: Number;
   sex: Number;
   creationTime: String;
   morningWorking: Number;
   morningStartAt: String;
   morningEndAt: String;
   afternoonWorking: Number;
   afternoonStartAt: String;
   afternoonEndAt: String;
   generateAuthToken: () => Promise<string>;
   comparePassHash: (plainPass: string) => Promise<Boolean>;
}
