import { validQueryID, validQueryInput } from '../middlewares/validate/FieldValidate';
import { validate } from '../middlewares/validate/FieldValidate';
// import TimekeepingService from '../services/TimekeepingService';
import { BaseRouter } from './BaseRouter';

const FAKE_MUDETAILS = {
   result: [
      {
         timekeepingId: 17599,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-27T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 17336,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-25T00:00:00+07:00',
         registrationTimeStart: '10:00',
         registrationTimeEnd: '12:00',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 0,
         userNote: null,
         noteReply: ' Saturday',
      },
      {
         timekeepingId: 16973,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-24T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 16610,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-23T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 16253,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-22T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 15902,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-21T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 15559,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-20T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 15292,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-18T00:00:00+07:00',
         registrationTimeStart: '10:00',
         registrationTimeEnd: '12:00',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 0,
         userNote: null,
         noteReply: ' Saturday',
      },
      {
         timekeepingId: 14941,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-17T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 14594,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-16T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 14252,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-15T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 13576,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-14T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 13246,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-13T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 12980,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-11T00:00:00+07:00',
         registrationTimeStart: '10:00',
         registrationTimeEnd: '12:00',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 0,
         userNote: null,
         noteReply: ' Saturday',
      },
      {
         timekeepingId: 12662,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-10T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 12341,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-09T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 12021,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-08T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 11709,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-07T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 11402,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-06T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 10917,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-04T00:00:00+07:00',
         registrationTimeStart: '10:00',
         registrationTimeEnd: '12:00',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 0,
         userNote: null,
         noteReply: ' Saturday',
      },
      {
         timekeepingId: 10701,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-03T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: 174,
         editByUserName: 'admindev',
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 10475,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-02T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
      {
         timekeepingId: 11075,
         userId: 174,
         userName: 'huy admin',
         userType: null,
         userEmail: 'quanghuynb2@gmail.com',
         avatarPath: '/avatars/1630052510000_174_admindev.jpg',
         branch: 0,
         date: '2021-09-01T00:00:00+07:00',
         registrationTimeStart: '08:30',
         registrationTimeEnd: '17:30',
         checkIn: null,
         checkOut: null,
         resultCheckIn: 0.0,
         resultCheckOut: 0.0,
         editByUserId: null,
         editByUserName: null,
         status: 1,
         userNote: null,
         noteReply: null,
      },
   ],
   targetUrl: null,
   success: true,
   error: null,
   unAuthorizedRequest: false,
   __abp: true,
};

class TimekeepingRouter extends BaseRouter {
   // private _service = TimekeepingService;
   constructor() {
      super();
      this.init();
   }

   protected init() {
      this.router.get('/GetMyDetails', (req, res) => {
         return res.status(200).json(FAKE_MUDETAILS);
      });
   }
}

export = new TimekeepingRouter().router;
