export const APP = {
   VERSION: '1.0.0.0',
   RELASE_DATE: '2021-07-20T15:49:07.1350156+07:00',
};

export const TOKEN_EXPIRE = 8640000;

export const WORKING_TIME = {
   '0': {
      morningStartAt: '08:30',
      morningEndAt: '12:00',
      afternoonStartAt: '13:00',
      afternoonEndAt: '17:30',
      morningWorking: '3.5',
      afternoonWorking: '4.5',
      id: 0,
   },
   '1': {
      morningStartAt: '08:00',
      morningEndAt: '12:00',
      afternoonStartAt: '13:00',
      afternoonEndAt: '17:00',
      morningWorking: '4',
      afternoonWorking: '4',
      id: 0,
   },
   '2': {
      morningStartAt: '08:30',
      morningEndAt: '12:00',
      afternoonStartAt: '13:00',
      afternoonEndAt: '17:30',
      morningWorking: '3.5',
      afternoonWorking: '4.5',
      id: 0,
   },
   '3': {
      morningStartAt: '08:30',
      morningEndAt: '12:00',
      afternoonStartAt: '13:00',
      afternoonEndAt: '17:30',
      morningWorking: '3.5',
      afternoonWorking: '4.5',
      id: 0,
   },
};

export const FAKE_MANAGERS = {
   result: [
      {
         name: 'Tien Pham',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 15,
         userCode: null,
         avatarPath: '/avatars/1632474098451_1_tien.pham.jpg',
         branch: null,
         id: 1,
      },
      {
         name: 'Tien Nguyen Huu',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 15,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 5,
      },
      {
         name: 'Thai Bui Minh',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 14,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 10,
      },
      {
         name: 'duong nghi viec giua thang 5',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 9,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 21,
      },
      {
         name: 'duong nghi viec giua thang 5',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 9,
         userCode: 'acsdc',
         avatarPath: '',
         branch: null,
         id: 22,
      },
      {
         name: 'NCCOP Sir',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 10,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 23,
      },
      {
         name: 'Bui Lam',
         isActive: false,
         type: 0,
         jobTitle: null,
         level: 5,
         userCode: '',
         avatarPath: '',
         branch: null,
         id: 24,
      },
      {
         name: 'Uno VATest',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 9,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 48,
      },
      {
         name: 'duong duong',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 0,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 84,
      },
      {
         name: 'thao1212 thaoo',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 0,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 93,
      },
      {
         name: 'thy phan',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 6,
         userCode: 'thy11',
         avatarPath: '',
         branch: null,
         id: 118,
      },
      {
         name: 'Dai Trinh',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: null,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 181,
      },
      {
         name: 'hien pm1',
         isActive: true,
         type: 0,
         jobTitle: null,
         level: 7,
         userCode: null,
         avatarPath: '',
         branch: null,
         id: 219,
      },
   ],
   targetUrl: null,
   success: true,
   error: null,
   unAuthorizedRequest: false,
   __abp: true,
};

export const ADMIN_PASSWORD = '123qwe';

export const REQUIRED_FIELD_LOGIN = ['password', 'userNameOrEmailAddress'];
export const REQUIRED_FIELD_RESET_PASS = ['adminPassword', 'newPassword', 'userId'];
export const REQUIRED_FIELD_SAVE_CUSTOMER = ['name', 'address'];
export const REQUIRED_FIELD_SAVE_TASK = ['name', 'type'];
export const REQUIRED_FIELD_CREATE_ROLE = ['description', 'displayName', 'name'];
export const REQUIRED_FIELD_CREATE_MYTIMSHEETS = [
   'dateAt',
   'projectTaskId',
   'workingTime',
   'typeOfWork',
   'targetUserWorkingTime',
];
export const REQUIRED_FIELD_SUBMIT_MYTIMSHEETS = ['startDate', 'endDate'];
export const SEARCH_TEXT_FIELD_PROJECTS = ['customerName', 'name'];
export const SEARCH_TEXT_FIELD_USER = ['userName', 'name', 'surname', 'emailAddress'];
